// ============================================================
// BANCO DE PERGUNTAS — PRONOMES (Língua Portuguesa)
// 8 níveis de dificuldade crescente, 10 perguntas cada.
//   t = tema | p = pergunta | a = alternativas (a[0] é SEMPRE a correta) | e = explicação
// Usado por: show-do-milhao.html e the-wall.html
// ============================================================
const NIVEIS = [
  "Reconhecer",
  "Classificar",
  "Átonos e tônicos",
  "Tratamento",
  "Colocação",
  "Transformar frases",
  "Indefinidos",
  "Análise fina"
];

const BANCO = [
// ---------- NÍVEL 1 — reconhecimento direto ----------
[
 {t:"Pronomes pessoais", p:"“Eu, tu, ele, nós, vós, eles” são pronomes pessoais do caso...",
  a:["reto","oblíquo átono","oblíquo tônico","de tratamento"],
  e:"Os pronomes do caso <b>reto</b> funcionam como sujeito da oração."},
 {t:"Pronomes possessivos", p:"Qual é o pronome possessivo correspondente à 1ª pessoa do singular?",
  a:["meu(s), minha(s)","teu(s), tua(s)","nosso(s), nossa(s)","seu(s), sua(s)"],
  e:"Eu → <b>meu(s), minha(s)</b>. Tu → teu/tua. Nós → nosso/nossa."},
 {t:"Pronomes de tratamento", p:"“Você”, “Senhor” e “Vossa Excelência” são pronomes de...",
  a:["tratamento","posse","interrogação","dúvida"],
  e:"Pronomes de <b>tratamento</b> servem para se dirigir à outra pessoa conforme a situação, o cargo, o título e a idade."},
 {t:"Tipos de pronomes", p:"“Este, esse, aquele, isto, isso, aquilo” são pronomes...",
  a:["demonstrativos","indefinidos","interrogativos","de tratamento"],
  e:"Pronomes <b>demonstrativos</b> situam um elemento no espaço, no tempo ou no discurso."},
 {t:"Conceito", p:"O que é um pronome?",
  a:["O termo que substitui ou acompanha o substantivo","A palavra que indica ação","A palavra que liga duas orações","A palavra que dá qualidade ao verbo"],
  e:"Pronome é o termo que <b>substitui ou acompanha</b> o substantivo, indicando pessoa do discurso, posse ou posição."},
 {t:"Pronomes pessoais", p:"Qual é a função dos pronomes pessoais?",
  a:["Substituir os substantivos e indicar as pessoas do discurso","Ligar duas orações","Indicar circunstância de tempo","Dar qualidade ao substantivo"],
  e:"Eles <b>substituem os substantivos</b> e indicam quem fala, com quem se fala e de quem se fala."},
 {t:"Pronomes pessoais", p:"Qual pronome do caso reto corresponde à 2ª pessoa do plural?",
  a:["vós","nós","eles","tu"],
  e:"1ª sing. eu · 2ª sing. tu · 3ª sing. ele/ela · 1ª pl. nós · 2ª pl. <b>vós</b> · 3ª pl. eles/elas."},
 {t:"Tipos de pronomes", p:"“Que, o qual, cujo, quem, onde” retomam algo já dito na frase. São pronomes...",
  a:["relativos","interrogativos","possessivos","de tratamento"],
  e:"Pronomes <b>relativos</b> retomam um termo anterior da frase."},
 {t:"Tipos de pronomes", p:"“Qual? Quanto? Quem? Que?” usados em perguntas são pronomes...",
  a:["interrogativos","relativos","demonstrativos","indefinidos"],
  e:"Pronomes <b>interrogativos</b> indicam perguntas diretas ou indiretas."},
 {t:"Pessoas do discurso", p:"A pessoa do discurso “com quem se fala” é a...",
  a:["segunda pessoa (tu, vós)","primeira pessoa (eu, nós)","terceira pessoa (ele, eles)","nenhuma delas"],
  e:"1ª pessoa: quem fala. <b>2ª pessoa: com quem se fala.</b> 3ª pessoa: de quem se fala."}
],
// ---------- NÍVEL 2 — classificação simples ----------
[
 {t:"Pronomes pessoais", p:"Em “Ele <i>me</i> deu um livro”, o pronome “me” é um pronome oblíquo...",
  a:["átono","tônico","reto","possessivo"],
  e:"Oblíquos <b>átonos</b> não vêm acompanhados de preposição: me, te, o, a, lhe, se, nos, vos, os, as, lhes."},
 {t:"Pronomes indefinidos", p:"Em “<i>Ninguém</i> mais se ocupa de mim”, a palavra destacada é um pronome...",
  a:["indefinido","demonstrativo","relativo","possessivo"],
  e:"Pronomes <b>indefinidos</b> se referem à 3ª pessoa de forma vaga ou imprecisa."},
 {t:"Pronomes pessoais", p:"Em “<i>Nós</i> fomos ao cinema”, o pronome “nós” exerce a função de...",
  a:["sujeito","objeto direto","adjunto adnominal","complemento nominal"],
  e:"Quando o pronome pessoal é <b>sujeito</b>, ele é do caso reto."},
 {t:"Pronomes indefinidos", p:"Qual destes pronomes indefinidos é INVARIÁVEL?",
  a:["ninguém","algum","muitas","certos"],
  e:"São invariáveis: algo, alguém, cada, mais, menos, nada, <b>ninguém</b>, outrem, tudo."},
 {t:"Pronomes pessoais", p:"De acordo com a função que exercem, os pronomes pessoais dividem-se em...",
  a:["retos, oblíquos e de tratamento","retos, relativos e possessivos","átonos, tônicos e indefinidos","simples, compostos e mistos"],
  e:"Os pronomes pessoais podem ser <b>retos, oblíquos</b> (átonos ou tônicos) <b>e de tratamento</b>."},
 {t:"Pronomes possessivos", p:"Em “Não deixe <i>sua</i> cadela ir à <i>minha</i> casa!”, os termos destacados são pronomes...",
  a:["possessivos, pois indicam posse","demonstrativos, pois indicam posição","indefinidos, pois são vagos","de tratamento, pois são formais"],
  e:"Pronomes <b>possessivos</b> se referem a uma das três pessoas do discurso para indicar posse."},
 {t:"Pronomes indefinidos", p:"Em “Bastaria esse <i>alguém</i> pegá-la e levá-la”, “alguém” é um pronome indefinido...",
  a:["invariável","variável em gênero","variável em número","variável em gênero e número"],
  e:"“Alguém” não flexiona: é <b>invariável</b>, assim como algo, nada, tudo, ninguém e outrem."},
 {t:"Pronomes pessoais", p:"Qual é o pronome oblíquo átono correspondente a “nós”?",
  a:["nos","conosco","nosso","vos"],
  e:"Átono: <b>nos</b>. Tônico: conosco. “Nosso” é possessivo, não pessoal."},
 {t:"Pronomes demonstrativos", p:"“Este, esta, isto” indicam algo que está...",
  a:["perto de quem fala","perto de quem ouve","distante dos dois","fora do discurso"],
  e:"<b>Este/esta/isto</b> = perto do locutor · esse/essa/isso = perto do interlocutor · aquele/aquela/aquilo = distante dos dois."},
 {t:"Pronomes demonstrativos", p:"Em “Fafá, não vá mais a <i>essa</i> casa”, o termo destacado indica...",
  a:["posição — é pronome demonstrativo","posse — é pronome possessivo","pessoa — é pronome pessoal","quantidade — é pronome indefinido"],
  e:"“Essa” indica <b>posição</b>: refere-se à casa de Dona Severa, um local. É demonstrativo."}
],
// ---------- NÍVEL 3 — átonos × tônicos ----------
[
 {t:"Oblíquos tônicos", p:"Em “Trouxe essa rosa para <i>ti</i>”, o pronome “ti” é oblíquo...",
  a:["tônico, porque vem acompanhado de preposição","átono, porque é curto","reto, porque é sujeito","de tratamento, porque é formal"],
  e:"Os oblíquos <b>tônicos</b> exigem preposição: mim, comigo, ti, contigo, si, consigo, conosco, convosco."},
 {t:"Oblíquos tônicos", p:"Por que NÃO se diz “com comigo”?",
  a:["Porque a preposição “com” já faz parte da palavra “comigo”","Porque “comigo” é pronome reto","Porque “comigo” é possessivo","Porque “comigo” não aceita preposição nenhuma"],
  e:"Em comigo, contigo, consigo, conosco e convosco a <b>preposição já está incorporada</b> à palavra."},
 {t:"Oblíquos tônicos", p:"Em “A pescaria era uma boa atividade para <i>ele</i>”, o pronome “ele” é...",
  a:["oblíquo tônico, pois é complemento com preposição","reto, pois é sujeito","átono, pois não tem preposição","possessivo, pois indica posse"],
  e:"“Ele/ela/nós/vós” são retos quando são <b>sujeito</b> e oblíquos tônicos quando são <b>complemento com preposição</b>."},
 {t:"Átonos × tônicos", p:"Qual é a diferença entre pronomes oblíquos átonos e tônicos?",
  a:["Os tônicos exigem preposição; os átonos, não","Os átonos são sempre sujeito","Os tônicos só aparecem no plural","Os átonos vêm sempre no fim da frase"],
  e:"Átonos não vêm acompanhados de preposição; <b>tônicos exigem</b> essa partícula."},
 {t:"Oblíquos átonos", p:"Qual alternativa apresenta APENAS pronomes oblíquos átonos?",
  a:["me, te, se, nos","mim, ti, si, conosco","eu, tu, ele, nós","meu, teu, seu, nosso"],
  e:"Átonos: me, te, o, a, lhe, se, nos, vos, os, as, lhes, se."},
 {t:"Oblíquos tônicos", p:"Em “Adoro caminhar <i>contigo</i>”, a palavra “contigo” equivale a...",
  a:["com + tigo (preposição “com”)","contra + tigo","conforme + tigo","com + ti + go"],
  e:"<b>Contigo = com + tigo</b>. Por isso não se usa outra preposição antes."},
 {t:"Oblíquos tônicos", p:"Qual destes pronomes é oblíquo TÔNICO?",
  a:["mim","me","o","lhe"],
  e:"<b>Mim</b> é tônico (para mim, de mim). Me, o e lhe são átonos."},
 {t:"Para mim / para eu", p:"Qual frase está de acordo com a norma-padrão?",
  a:["Ele trouxe um presente para mim.","Ele trouxe um presente para eu.","Ele trouxe um presente para mim ler.","Entre eu e você não há problema."],
  e:"Depois de preposição usa-se <b>mim</b>. Usa-se “eu” quando ele é sujeito de um verbo: “para <b>eu</b> ler”."},
 {t:"Preposições", p:"Qual das palavras a seguir é uma preposição essencial?",
  a:["perante","porque","quando","embora"],
  e:"São preposições essenciais: a, ante, após, até, com, contra, desde, de, em, entre, para, sem, por, <b>perante</b>, sob/sobre, trás."},
 {t:"Oblíquos", p:"Em “Ela pensou <i>consigo</i> mesma que deveria devolver a carteira”, “consigo” é...",
  a:["pronome oblíquo tônico de 3ª pessoa","pronome reto de 3ª pessoa","pronome de tratamento","pronome indefinido"],
  e:"<b>Consigo</b> é oblíquo tônico (com + sigo), referente à 3ª pessoa."}
],
// ---------- NÍVEL 4 — tratamento e pessoa do discurso ----------
[
 {t:"Pronomes de tratamento", p:"Qual pronome de tratamento é usado para o Presidente da República, senadores e deputados?",
  a:["Vossa Excelência","Vossa Magnificência","Vossa Eminência","Vossa Alteza"],
  e:"<b>Vossa Excelência</b> (V. Ex.ª) é usado para pessoas com alta autoridade."},
 {t:"Pronomes de tratamento", p:"“Vossa Magnificência” é o tratamento dirigido a...",
  a:["reitores de universidades","cardeais","reis e rainhas","príncipes e duques"],
  e:"V. Mag.ª → <b>reitores</b>. Cardeais → V. Em.ª. Reis → V. M. Príncipes e duques → V. A."},
 {t:"Pronomes de tratamento", p:"“Vossa Santidade” (V. S.) é o tratamento usado para...",
  a:["o Papa","cardeais","juízes","embaixadores"],
  e:"<b>Vossa Santidade</b> é reservado ao Papa. Para sacerdotes em geral, usa-se Vossa Reverendíssima."},
 {t:"Pronomes de tratamento", p:"Para se dirigir a reis e rainhas, usa-se...",
  a:["Vossa Majestade","Vossa Alteza","Vossa Senhoria","Vossa Eminência"],
  e:"<b>Vossa Majestade</b> (V. M.) → reis e rainhas. Vossa Alteza (V. A.) → príncipes, princesas e duques."},
 {t:"Concordância", p:"Ao usar o pronome de tratamento “você”, a concordância verbal deve ser feita...",
  a:["na 3ª pessoa: “você quer”","na 2ª pessoa: “você queres”","na 1ª pessoa: “você quero”","no plural: “você querem”"],
  e:"Apesar de indicarem a 2ª pessoa do discurso, os pronomes de tratamento levam o verbo para a <b>3ª pessoa</b>."},
 {t:"Concordância", p:"Segundo a norma-padrão, a construção “a gente” deve ser flexionada...",
  a:["no singular: “a gente foi ao cinema”","no plural: “a gente foram ao cinema”","sempre no futuro","sempre acompanhada de “nós”"],
  e:"“A gente” substitui “nós”, mas sua flexão é feita no <b>singular</b>, mesmo indicando mais de uma pessoa."},
 {t:"Abreviaturas", p:"A abreviatura “V. S.ª” corresponde a qual pronome de tratamento?",
  a:["Vossa Senhoria","Vossa Santidade","Vossa Senhora","Vossa Serenidade"],
  e:"<b>Vossa Senhoria</b> (V. S.ª) é empregado em textos escritos, como ofícios e requerimentos."},
 {t:"Mistura de pronomes", p:"Por que “Que bom <i>te</i> ver. O que <i>você</i> faz aqui?” é inadequado em contexto formal?",
  a:["Porque mistura pronomes de 2ª e 3ª pessoas no mesmo texto","Porque “te” não existe na norma-padrão","Porque “você” só pode ser usado por escrito","Porque falta um pronome possessivo"],
  e:"A norma-padrão pede <b>coerência</b>: escolhido “você”, mantém-se “o que <b>lhe</b> trouxe aqui”. Na fala informal a mistura é comum."},
 {t:"Pronomes de tratamento", p:"No quadrinho, o personagem usa “Seu Fernando” para demonstrar respeito. “Seu” é...",
  a:["uma variação informal de “Senhor”","um pronome possessivo","um pronome indefinido","um pronome relativo"],
  e:"“Seu” aqui é <b>variação informal de “Senhor”</b>, um pronome de tratamento."},
 {t:"Pronomes de tratamento", p:"Para substituir “rei dos memes” por um pronome de tratamento adequado, usaríamos...",
  a:["Vossa Majestade","Vossa Excelência","Vossa Magnificência","Vossa Reverendíssima"],
  e:"Reis recebem o tratamento de <b>Vossa Majestade</b>."}
],
// ---------- NÍVEL 5 — colocação pronominal ----------
[
 {t:"Colocação pronominal", p:"Qual frase está de acordo com a norma-padrão?",
  a:["Diga-me a verdade.","Me diga a verdade.","Me diz a verdade.","Me digas a verdade."],
  e:"Não se inicia frase com pronome oblíquo átono: nesses casos o pronome vem <b>depois</b> do verbo (ênclise)."},
 {t:"Colocação pronominal", p:"Em “Não <i>o</i> machuque”, por que o pronome aparece antes do verbo?",
  a:["Porque foi atraído pela palavra negativa “não”","Porque o verbo está no infinitivo","Porque o verbo termina em -r","Porque o sujeito está oculto"],
  e:"<b>Palavras negativas</b> (não, nunca, jamais) atraem o pronome oblíquo átono para antes do verbo."},
 {t:"Colocação pronominal", p:"Em “Eu <i>te</i> levarei ao cinema”, o que atraiu o pronome para antes do verbo?",
  a:["O pronome reto “eu”","O tempo futuro","A vírgula","O sujeito indeterminado"],
  e:"Os oblíquos átonos são atraídos por <b>pronomes retos</b>: “Eu te levarei”, “Ele se chama Antônio”."},
 {t:"Colocação pronominal", p:"Em “Há pessoas que <i>lhe</i> querem bem”, a próclise ocorre por causa...",
  a:["da palavra iniciada por qu- (“que”)","do verbo no infinitivo","do imperativo afirmativo","da ausência de sujeito"],
  e:"Palavras iniciadas por <b>qu-</b> (que, quem, quando) atraem o pronome para antes do verbo."},
 {t:"Colocação pronominal", p:"Com o verbo no imperativo afirmativo, o pronome oblíquo átono deve vir...",
  a:["depois do verbo: “conte-me tudo”","antes do verbo: “me conte tudo”","no meio do verbo","separado por vírgula"],
  e:"No <b>imperativo afirmativo</b> usa-se a ênclise: “Sente aqui e conte-me tudo”, “Convença-me do contrário”."},
 {t:"Colocação pronominal", p:"Com o verbo no infinitivo impessoal, o pronome oblíquo átono...",
  a:["pode vir antes ou depois do verbo","só pode vir depois do verbo","só pode vir antes do verbo","não pode ser usado"],
  e:"“Eu vou lhe contar um segredo” e “Eu vou contar-lhe um segredo”: <b>as duas formas</b> estão corretas."},
 {t:"Colocação pronominal", p:"Em “Nunca <i>se</i> deixe abater”, a próclise é explicada...",
  a:["pela palavra negativa “nunca”","pelo verbo no gerúndio","pela palavra iniciada por qu-","pelo pronome reto anterior"],
  e:"Não, nunca e jamais são <b>palavras negativas</b> e atraem o pronome para antes do verbo."},
 {t:"Colocação pronominal", p:"Em “Me desculpe, rei dos memes”, o problema em relação à norma-padrão é que...",
  a:["não se inicia frase com pronome oblíquo átono","“desculpe” não aceita pronome","“rei” exige Vossa Eminência","o pronome deveria ser possessivo"],
  e:"O correto seria “<b>Desculpe-me</b>”. Em contextos informais, porém, a próclise inicial é comum na fala."},
 {t:"Colocação pronominal", p:"Em “De que <i>se</i> trata esse trabalho?”, a próclise ocorre porque...",
  a:["a frase começa por palavra iniciada com qu-","há palavra negativa","o verbo está no imperativo","há um pronome possessivo"],
  e:"Palavras com <b>qu-</b> (que, quem, quando, quanto) atraem o pronome oblíquo átono."},
 {t:"Colocação pronominal", p:"Qual frase respeita a regra de colocação do pronome no início do período?",
  a:["Acorde-me amanhã cedo.","Me acorde amanhã cedo.","Me acordas amanhã cedo.","Amanhã me cedo acorde."],
  e:"Início de frase pede <b>ênclise</b>: “Acorde-me”, “Deixe-o sozinho”, “Trago-lhe essa rosa”."}
],
// ---------- NÍVEL 6 — transformar frases ----------
[
 {t:"Pronomes o/a e lhe", p:"Reescrevendo “Catarina comprou alguns livros” com pronome oblíquo átono, temos:",
  a:["Catarina comprou-os.","Catarina comprou-lhes.","Catarina comprou-nos.","Catarina os comprou-lhe."],
  e:"Se o verbo <b>não exige preposição</b>, usam-se “o(s)” e “a(s)”. Se exige, usa-se “lhe(s)”."},
 {t:"Pronomes o/a e lhe", p:"Em “Deu uma bronca nele, dizendo-<i>lhe</i> que deveria pescar mais”, usa-se “lhe” porque...",
  a:["o verbo exige preposição (dizer a ele)","o verbo termina em -r","há palavra negativa na frase","o pronome está no início da frase"],
  e:"Verbo com preposição → <b>lhe(s)</b>: “dizendo a ele” = “dizendo-lhe”."},
 {t:"Formas -lo/-la", p:"“A escritora vai publicar o livro amanhã.” Substituindo o trecho destacado:",
  a:["A escritora vai publicá-lo amanhã.","A escritora vai publicar-o amanhã.","A escritora vai publicar-no amanhã.","A escritora vai publicar-lhe amanhã."],
  e:"Com verbos terminados em <b>-r, -s, -z</b>, os pronomes o/a/os/as viram <b>lo, la, los, las</b>."},
 {t:"Formas -no/-na", p:"“As jogadoras venceram as partidas.” A forma correta com pronome é:",
  a:["As jogadoras venceram-nas.","As jogadoras venceram-as.","As jogadoras venceram-las.","As jogadoras venceram-lhes."],
  e:"Com verbos terminados em ditongo nasal (-am, -em, -ão, -õe), usam-se <b>no, na, nos, nas</b>."},
 {t:"Formas -no/-na", p:"Em “Até que um dia mataram-<i>na</i>”, o pronome assume a forma “na” porque o verbo...",
  a:["termina em ditongo nasal (-am)","termina em -r","exige preposição","está no infinitivo"],
  e:"“Mataram” termina em <b>-am</b> (som nasal), por isso “a” vira “<b>na</b>”."},
 {t:"Pronomes o/a e lhe", p:"“Os pais deram dinheiro <i>a cada um deles</i>.” Substituindo o trecho destacado:",
  a:["Os pais lhes deram dinheiro.","Os pais os deram dinheiro.","Os pais deram-nos dinheiro a eles.","Os pais deram-las dinheiro."],
  e:"“Dar <b>a</b> alguém” exige preposição, então usa-se <b>lhes</b>."},
 {t:"Formas -lo/-la", p:"“Se você mandar matar <i>esta galinha</i>...” Com pronome oblíquo átono fica:",
  a:["Se você mandar matá-la...","Se você mandar matar-a...","Se você mandar matar-lhe...","Se você mandar matar-na..."],
  e:"“Matar” termina em <b>-r</b>: o pronome vira <b>la</b> e o verbo perde o r → matá-la."},
 {t:"Formas -no/-na", p:"“Todos rodearam <i>a jovem parturiente</i>.” A reescrita correta é:",
  a:["Todos rodearam-na.","Todos rodearam-a.","Todos rodearam-la.","Todos rodearam-lhe."],
  e:"“Rodearam” termina em <b>-am</b>, ditongo nasal → o pronome “a” vira “<b>na</b>”."},
 {t:"Pronomes o/a e lhe", p:"Em “Encerrou a conversa afirmando-<i>lhe</i> que ela tinha o que fazer”, o “lhe” equivale a...",
  a:["“a ele” — o verbo exige preposição","“o” — o verbo não exige preposição","“dele” — indica posse","“ele” — é sujeito da oração"],
  e:"Afirmar <b>a</b> alguém → verbo com preposição → usa-se <b>lhe</b>."},
 {t:"Formas -lo/-la", p:"“Alice queria ver o coelho.” A forma correta com pronome é:",
  a:["Alice queria vê-lo.","Alice queria ver-o.","Alice queria ver-no.","Alice queria ver-lhe."],
  e:"Verbo terminado em <b>-r</b> → “o” vira “<b>lo</b>” e o verbo perde o r: vê-lo."}
],
// ---------- NÍVEL 7 — indefinidos em contexto ----------
[
 {t:"Pronomes indefinidos", p:"Qual alternativa contém APENAS pronomes indefinidos invariáveis?",
  a:["algo, alguém, nada, tudo","algum, muito, todo, vários","certo, outro, tanto, quanto","pouco, qualquer, diverso, bastante"],
  e:"Invariáveis: algo, alguém, cada, mais, menos, nada, ninguém, outrem, tudo. Os demais <b>flexionam</b>."},
 {t:"Locução pronominal", p:"Em “<i>Qualquer um</i> pode fazer mágicas com truques simples”, o trecho destacado é uma...",
  a:["locução pronominal","locução verbal","locução adjetiva","locução adverbial"],
  e:"Quando um <b>grupo de palavras</b> assume o valor de um pronome indefinido, temos uma locução pronominal: cada um, cada qual, seja quem for..."},
 {t:"Pronomes indefinidos", p:"Em “<i>Certo</i> dia, o garoto encontrou o caderno velho”, “certo” é pronome indefinido porque...",
  a:["está anteposto ao substantivo","está posposto ao substantivo","é invariável","vem depois do verbo"],
  e:"“Certo/certa” assume função de pronome indefinido quando vem <b>antes</b> do substantivo."},
 {t:"Pronomes indefinidos", p:"Qual frase tem valor NEGATIVO por causa da posição do pronome indefinido?",
  a:["Deputado algum defendeu a construção de novos abrigos.","Algum vereador defenderá a causa ambiental?","Todo jovem quer viajar.","Cada paciente aguardou sua vez."],
  e:"“Algum” <b>anteposto</b> ao substantivo tem valor afirmativo; <b>posposto</b>, valor negativo (= nenhum)."},
 {t:"Pronomes indefinidos", p:"Em “<i>Todo</i> o quarto estava sujo”, o pronome tem sentido de...",
  a:["totalidade: o quarto inteiro estava sujo","apenas uma parte do quarto","muitos quartos sujos","quarto nenhum estava sujo"],
  e:"No singular e posposto, “todo” indica <b>globalidade</b>; no plural, indica a soma de um conjunto."},
 {t:"Pronomes indefinidos", p:"O pronome indefinido “cada” serve para...",
  a:["assinalar um elemento pertencente a um conjunto","indicar posse","retomar um termo anterior","fazer uma pergunta"],
  e:"“<b>Cada</b> paciente aguardou sua vez.” Também pode intensificar: “Faz cada projeto!”."},
 {t:"Indefinidos no texto", p:"Em “O que não sugeria <i>nenhum</i> sentimento especial”, o indefinido reforça a ideia de...",
  a:["indiferença — ausência total de sentimento","alegria intensa","dúvida do narrador","posse do animal"],
  e:"“Nenhum” <b>nega por completo</b> a existência de sentimento, reforçando a indiferença da galinha."},
 {t:"Indefinidos no texto", p:"Em “Há <i>muito</i> tempo, houve um caçador...”, o pronome indefinido serve para...",
  a:["situar a história num passado impreciso, típico dos contos","marcar uma data exata","indicar posse do caçador","fazer uma pergunta ao leitor"],
  e:"O indefinido dá <b>imprecisão temporal</b>, característica do gênero conto popular."},
 {t:"Pronomes indefinidos", p:"Em “A mulher foi conferir se as armadilhas tinham <i>alguma</i> presa”, “alguma” é indefinido...",
  a:["variável, pois flexiona em gênero e número","invariável, pois nunca muda","de tratamento, pois é formal","relativo, pois retoma um termo"],
  e:"Algum, alguma, alguns, algumas — flexiona, portanto é <b>variável</b>."},
 {t:"Locução pronominal", p:"Qual das opções NÃO é uma locução pronominal indefinida?",
  a:["por causa de","cada qual","todo aquele que","seja quem for"],
  e:"São locuções pronominais: cada um, cada qual, qualquer um, quem quer que, seja quem for, todo aquele que, todo mundo, um ou outro."}
],
// ---------- NÍVEL 8 — análise fina ----------
[
 {t:"Ambiguidade", p:"“O Lucas e a <i>sua</i> irmã andando no shopping.” Para deixar claro que a irmã é do Lucas, escreve-se:",
  a:["O Lucas e a irmã dele andando no shopping.","Sua irmã e o Lucas andando no shopping.","O Lucas e a irmã sua andando no shopping.","O Lucas e a irmã tua andando no shopping."],
  e:"“Seu/sua” pode se referir à 2ª ou à 3ª pessoa, gerando ambiguidade. “<b>Dele</b>” desfaz a dúvida."},
 {t:"Possessivos", p:"Sobre as palavras “dele” e “dela”, é correto afirmar que...",
  a:["não são possessivos, e sim a contração da preposição “de” com “ele/ela”","são possessivos de 3ª pessoa","são pronomes de tratamento","são pronomes indefinidos invariáveis"],
  e:"“Dele/dela” = <b>de + ele/ela</b>. São contrações, ainda que indiquem posse."},
 {t:"Valor possessivo", p:"Em “Cada vez que esse olho me fitava, sentia gelar-<i>me</i> o sangue”, o pronome “me” tem valor...",
  a:["possessivo (= meu sangue)","de sujeito","de tratamento","indefinido"],
  e:"Oblíquos átonos podem ter <b>valor possessivo</b>: “gelar-me o sangue” = “meu sangue gelar”."},
 {t:"Valor emotivo", p:"Em “<i>Minha</i> senhora, posso te ajudar a atravessar a rua?”, o possessivo indica...",
  a:["respeito e afetividade, e não posse","que a senhora pertence à jovem","uma dúvida do falante","uma quantidade indeterminada"],
  e:"Os possessivos também exprimem <b>valor emotivo</b>: respeito, admiração, afetividade ou ironia."},
 {t:"Possessivos", p:"Em “Não invejo seu dinheiro, pois tenho <i>o meu</i>”, o possessivo destacado é...",
  a:["substantivo, porque substitui o substantivo “dinheiro”","adjetivo, porque acompanha o substantivo","um pronome de tratamento","um pronome relativo"],
  e:"O possessivo <b>substantivo</b> substitui o substantivo para não repeti-lo na frase."},
 {t:"Concordância do possessivo", p:"Em “Lucas e Pedro são game players. <i>Seu</i> videogame é o Nintendo Switch”, o possessivo concorda:",
  a:["na 3ª pessoa com os possuidores e no masculino singular com “videogame”","no plural, porque são dois possuidores","no feminino, porque “pessoa” é feminino","apenas com o verbo da oração"],
  e:"O possessivo concorda em <b>pessoa</b> com o possuidor e em <b>gênero e número</b> com o substantivo pertencente."},
 {t:"Colocação pronominal", p:"Em “Ele <i>se</i> chama Antônio”, o pronome “se” é...",
  a:["oblíquo átono, atraído pelo pronome reto “ele”","oblíquo tônico, exigido por preposição","possessivo de 3ª pessoa","indefinido invariável"],
  e:"“Se” é <b>oblíquo átono</b> e foi atraído pelo pronome reto que o antecede."},
 {t:"Sentido do possessivo", p:"Em “Na <i>minha</i> escola, temos aulas de Português”, o possessivo indica que...",
  a:["há uma relação entre o falante e a escola, não propriedade","o falante é dono da escola","a escola pertence à turma","a escola é indefinida"],
  e:"Os possessivos <b>nem sempre indicam propriedade</b>: aqui apenas relacionam o falante à escola."},
 {t:"Ambiguidade", p:"Em “Alice se alvoroçou quando o Coelho sacou um relógio do bolso de <i>seu</i> colete”, o possessivo pode gerar ambiguidade porque...",
  a:["o colete pode ser do Coelho ou do interlocutor","“seu” não é pronome possessivo","“colete” é palavra feminina","o verbo está no passado"],
  e:"“Seu/sua” faz referência tanto à 2ª quanto à 3ª pessoa — daí a <b>ambiguidade</b>."},
 {t:"Análise em contexto", p:"Em “Um tio dela que morava na França <i>a</i> chamou para passar um tempo com <i>ele</i>”, os pronomes destacados são, respectivamente:",
  a:["oblíquo átono e oblíquo tônico","oblíquo tônico e reto","reto e possessivo","possessivo e átono"],
  e:"“A” é <b>átono</b> (sem preposição) e “ele”, depois de “com”, é <b>oblíquo tônico</b>."}
]
];
