'use strict';
const gameRoot=document.getElementById('game');
const gameSelect=document.getElementById('game-select');
let round=0;
function feedback(text){gameRoot.querySelector('.answer').textContent=text;}
function resetGame(){round=0;renderGame();}
gameSelect.addEventListener('change',resetGame);
function nextRound(){round++;renderGame();}
function tail(hint){return `<div class="answer" role="status" aria-live="polite">Sua vez! Pense, experimente e explique.</div><details><summary>Uma pista</summary><p>${hint}</p></details><button class="next">Próximo desafio</button>`;}
function bindNext(){gameRoot.querySelector('.next').onclick=nextRound;}
function renderGame(){({coins:coinsGame,fractions:fractionsGame,area:areaGame,nim:nimGame,operations:operationsGame,balance:balanceGame,logic:logicGame,space:spaceGame})[gameSelect.value]();}
function coinsGame(){
 const rounds=[[12,2,3],[15,2,3],[18,3,4],[24,3,5],[30,4,6]];
 const [total,a,b]=rounds[round%rounds.length];const expected=[];const found=new Set();
 for(let x=0;x*a<=total;x++)for(let y=0;x*a+y*b<=total;y++)if(x*a+y*b===total)expected.push([x,y]);
 gameRoot.innerHTML=`<span class="pill">Contagem · desafio ${round%rounds.length+1} de ${rounds.length}</span><h3>Caixa sem troco</h3><p class="mission">Encontre todas as maneiras de pagar ${total} moedas.</p><p>Use fichas de ${a} e de ${b}. Pode usar zero de um tipo. A ordem não importa: conte apenas as quantidades de cada ficha.</p><form class="row"><label>Fichas de ${a}: <input id="coin-a" type="number" min="0" max="${Math.floor(total/a)}" value="0" required></label><label>Fichas de ${b}: <input id="coin-b" type="number" min="0" max="${Math.floor(total/b)}" value="0" required></label><button class="primary">Registrar combinação</button></form><p id="found">0 combinações encontradas</p><ul id="combos"></ul>${tail(`Escolha primeiro quantas fichas de ${b} usar: 0, 1, 2… Veja se o que falta é divisível por ${a}.`)}`;
 gameRoot.querySelector('form').onsubmit=e=>{e.preventDefault();const x=Number(gameRoot.querySelector('#coin-a').value),y=Number(gameRoot.querySelector('#coin-b').value);if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0){feedback('Use quantidades inteiras e não negativas.');return;}const sum=x*a+y*b;if(sum!==total){feedback(`Essa combinação vale ${sum}. ${sum<total?'Faltam '+(total-sum):'Sobram '+(sum-total)} moedas. Ajuste as fichas.`);return;}const key=x+','+y;if(found.has(key)){feedback('Você já registrou essa combinação. Procure uma quantidade diferente de fichas.');return;}found.add(key);const li=document.createElement('li');li.textContent=`${x} × ${a} + ${y} × ${b} = ${total}`;gameRoot.querySelector('#combos').append(li);gameRoot.querySelector('#found').textContent=`${found.size} combinações encontradas`;feedback(found.size===expected.length?`Você encontrou todas as ${expected.length} combinações! Agora explique como sua lista garante que nenhuma ficou de fora.`:'Combinação válida! Há outras possibilidades. Continue a lista em ordem.');};bindNext();
}
function fractionsGame(){
 const rounds=[[12,1,3],[12,3,4],[16,3,8],[20,2,5],[24,5,6]];const [n,p,q]=rounds[round%rounds.length];const target=n*p/q;const selected=new Set();
 gameRoot.innerHTML=`<span class="pill">Frações · desafio ${round%rounds.length+1} de ${rounds.length}</span><h3>Mosaico de frações</h3><p class="mission">Pinte ${p}/${q} deste mosaico.</p><p>O inteiro é o mosaico todo: ${n} quadradinhos iguais. Clique para pintar ou apagar. A posição não importa.</p><div class="gameboard" style="grid-template-columns:repeat(${n===16?4:n===20?5:6},1fr)">${Array.from({length:n},(_,i)=>`<button class="cell" aria-label="Quadradinho ${i+1}" aria-pressed="false" data-i="${i}">${i+1}</button>`).join('')}</div><p id="paint-count">0 de ${n} pintados</p><button class="check primary">Conferir mosaico</button>${tail(`Divida os ${n} quadradinhos em ${q} grupos iguais. Depois use ${p} desses grupos.`)}`;
 gameRoot.querySelectorAll('.cell').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.i);if(selected.has(i))selected.delete(i);else selected.add(i);b.classList.toggle('on',selected.has(i));b.setAttribute('aria-pressed',String(selected.has(i)));gameRoot.querySelector('#paint-count').textContent=`${selected.size} de ${n} pintados`;feedback('Confira quando terminar de pintar.');});gameRoot.querySelector('.check').onclick=()=>feedback(selected.size===target?`Isso! ${n} ÷ ${q} × ${p} = ${target}. Você pintou ${target}/${n}, que equivale a ${p}/${q}. Explique essa equivalência com grupos.`:`Você pintou ${selected.size}/${n}. Pense em ${q} grupos iguais e selecione ${p} deles.`);bindNext();
}
function perimeter(cells){let result=0;for(const key of cells){const [r,c]=key.split(',').map(Number);for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]])if(!cells.has((r+dr)+','+(c+dc)))result++;}return result;}
function connected(cells){if(!cells.size)return false;const seen=new Set();const queue=[cells.values().next().value];while(queue.length){const key=queue.pop();if(seen.has(key))continue;seen.add(key);const [r,c]=key.split(',').map(Number);for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const next=(r+dr)+','+(c+dc);if(cells.has(next)&&!seen.has(next))queue.push(next);}}return seen.size===cells.size;}
function areaGame(){
 const rounds=[[6,10],[6,14],[8,12],[8,18],[9,12]];const [a,p]=rounds[round%rounds.length];const cells=new Set();
 gameRoot.innerHTML=`<span class="pill">Geometria · desafio ${round%rounds.length+1} de ${rounds.length}</span><h3>Arquiteto do quadriculado</h3><p class="mission">Área ${a} e perímetro ${p}.</p><p>Cada quadradinho tem lado 1. Construa uma figura só, com peças ligadas por lados. Clique para colocar ou retirar peças. O contorno de buracos também conta no perímetro.</p><div class="gameboard" style="grid-template-columns:repeat(6,1fr)">${Array.from({length:36},(_,i)=>`<button class="cell" data-key="${Math.floor(i/6)},${i%6}" aria-label="Linha ${Math.floor(i/6)+1}, coluna ${i%6+1}" aria-pressed="false"></button>`).join('')}</div><p id="measure">Área: 0 · Perímetro: 0</p><button class="check primary">Conferir construção</button>${tail('Cada quadradinho isolado tem 4 lados. Cada lado compartilhado entre dois quadradinhos diminui o perímetro total em 2. Figuras compactas costumam ter menos borda.')}`;
 gameRoot.querySelectorAll('.cell').forEach(b=>b.onclick=()=>{const key=b.dataset.key;if(cells.has(key))cells.delete(key);else cells.add(key);b.classList.toggle('on',cells.has(key));b.setAttribute('aria-pressed',String(cells.has(key)));gameRoot.querySelector('#measure').textContent=`Área: ${cells.size} · Perímetro: ${perimeter(cells)}`;feedback('Observe o que mudou na área e no contorno.');});gameRoot.querySelector('.check').onclick=()=>{if(!connected(cells)){feedback('Una todas as peças por lados para formar uma única figura.');return;}feedback(cells.size===a&&perimeter(cells)===p?`Construção concluída! Área ${a} e perímetro ${p}. Desenhe no papel e explique quais lados entram no contorno.`:`Sua figura tem área ${cells.size} e perímetro ${perimeter(cells)}. A missão pede área ${a} e perímetro ${p}. Experimente reorganizar as peças.`);};bindNext();
}
function nimGame(){
 const starts=[15,12,17,16,11];let left=starts[round%starts.length];let ended=false;
 gameRoot.innerHTML=`<span class="pill">Estratégia · desafio ${round%starts.length+1} de ${starts.length}</span><h3>Último palito</h3><p class="mission">Quem retira o último vence.</p><p>Você começa. Em cada turno, retire 1, 2 ou 3 palitos. O computador joga em seguida e procura deixar um múltiplo de 4. Alguns inícios permitem que ele vença mesmo que você jogue bem: investigue quais são!</p><div class="tokens" aria-hidden="true"></div><p id="remaining"></p><div class="row">${[1,2,3].map(n=>`<button data-take="${n}" class="primary">Retirar ${n}</button>`).join('')}</div>${tail('Imagine que seu adversário recebe 4 palitos. Independentemente do que ele retire, você consegue pegar os que restarem. Como deixar 8, 12 ou 16 para ele?')}<details><summary>Entender a estratégia depois de jogar</summary><p>As posições 4, 8, 12, 16… são desfavoráveis para quem vai jogar, se o adversário responder corretamente. A cada retirada de k palitos, ele retira 4 − k. Assim, os dois retiram 4 por par de turnos. Se você começa com 15, retire 3 e deixe 12. Se começa com 12, não há vitória garantida contra um adversário que siga essa estratégia. Quando o computador recebe um múltiplo de 4, ele retira 1.</p></details>`;
 function paint(){gameRoot.querySelector('.tokens').innerHTML='<span class="token"></span>'.repeat(left);gameRoot.querySelector('#remaining').textContent=`${left} palitos restantes`;gameRoot.querySelectorAll('[data-take]').forEach(b=>b.disabled=ended||Number(b.dataset.take)>left);}
 gameRoot.querySelectorAll('[data-take]').forEach(b=>b.onclick=()=>{if(ended)return;const k=Number(b.dataset.take);if(k>left)return;left-=k;if(left===0){ended=true;paint();feedback('Você retirou o último e venceu! Quais quantidades deixou para o computador? Explique a estratégia.');return;}const take=left%4||1;left-=take;if(left===0){ended=true;feedback(`Você retirou ${k}. O computador retirou ${take}, pegou o último e venceu. Investigue os múltiplos de 4 na pista e tente outro início.`);}else feedback(`Você retirou ${k}; o computador retirou ${take}. Restam ${left}. Sua vez!`);paint();});paint();bindNext();
}
