'use strict';
function operationsGame(){
 const start=7+(round*7)%19,a=3+round%7,b=2+round%4,c=5+round%9;const goal=(start+a)*b-c;let value=goal,step=0;
 const actions=[{label:`Somar ${c}`,apply:v=>v+c},{label:`Dividir por ${b}`,apply:v=>v/b},{label:`Subtrair ${a}`,apply:v=>v-a}];
 gameRoot.innerHTML=`<span class="pill">Operações e medidas · missão ${round+1}</span><h3>Máquina ao contrário</h3><p>A máquina escondeu o número inicial. Desfaça uma operação por vez, começando pela última.</p><div class="route"><strong>?</strong><span>→ +${a}</span><span>→ ×${b}</span><span>→ −${c}</span><strong>→ ${goal}</strong></div><p class="mission">Voltando: <span id="machine-value">${goal}</span></p><p id="machine-steps">Nenhuma operação desfeita.</p><div class="row">${[2,0,1].map(i=>`<button data-inverse="${i}">${actions[i].label}</button>`).join('')}</div>${tail('A última operação foi uma subtração. Desfaça-a com uma adição. Depois desfaça a multiplicação; por último, a primeira adição.')}`;
 gameRoot.querySelectorAll('[data-inverse]').forEach(btn=>btn.onclick=()=>{if(step===3)return;const i=+btn.dataset.inverse;if(i!==step){feedback(`Ainda não. Agora precisamos desfazer ${['a subtração final','a multiplicação','a primeira adição'][step]}. Qual é a operação inversa?`);return;}value=actions[i].apply(value);step++;gameRoot.querySelector('#machine-value').textContent=value;gameRoot.querySelector('#machine-steps').textContent=actions.slice(0,step).map(x=>x.label).join(' → ');btn.disabled=true;feedback(step===3?`Você recuperou ${start}! Verificação: (${start} + ${a}) × ${b} − ${c} = ${goal}. Escreva essa conferência no papel.`:`Isso! Agora estamos em ${value}. Continue voltando pela máquina.`);});bindNext();
}
function balanceGame(){
 const a=2+(round*3)%11,b=3+(round*5)%13,t1=2*a+b,t2=a+2*b;
 gameRoot.innerHTML=`<span class="pill">Proporções e relações · missão ${round+1}</span><h3>Oficina das balanças</h3><p>Cada bloco A tem o mesmo peso; cada bloco B também. Descubra os pesos que equilibram as duas balanças ao mesmo tempo.</p><div class="balance">A + A + B = ${t1} kg</div><div class="balance">A + B + B = ${t2} kg</div><form class="row"><label>Bloco A (kg) <input id="weight-a" type="number" min="0" max="100" required value="0"></label><label>Bloco B (kg) <input id="weight-b" type="number" min="0" max="100" required value="0"></label><button class="primary">Testar os pesos</button></form><svg id="balance-view" class="plot-svg" viewBox="0 0 420 120" role="img" aria-label="Diferenças de peso das duas balanças"></svg>${tail(`Some as duas igualdades: três blocos A e três B pesam ${t1+t2} kg. Assim, um A mais um B pesam ${(t1+t2)/3} kg. Compare com a primeira balança.`)}`;
 gameRoot.querySelector('form').onsubmit=e=>{e.preventDefault();const x=+gameRoot.querySelector('#weight-a').value,y=+gameRoot.querySelector('#weight-b').value;const d1=2*x+y-t1,d2=x+2*y-t2;gameRoot.querySelector('#balance-view').innerHTML=[d1,d2].map((d,i)=>{const cx=105+i*210,tilt=Math.max(-20,Math.min(20,d*2));return `<path d="M${cx-12},85 L${cx},40 L${cx+12},85 Z" fill="#12675b"/><line x1="${cx-70}" y1="${40-tilt}" x2="${cx+70}" y2="${40+tilt}" stroke="#182f38" stroke-width="4"/><text x="${cx}" y="110" text-anchor="middle" fill="#182f38" font-size="13">${i+1}ª: ${d===0?'equilibrada':d>0?d+' kg a mais':(-d)+' kg a menos'}</text>`;}).join('');feedback(d1===0&&d2===0?`As duas equilibraram! A pesa ${a} kg e B pesa ${b} kg. Explique como descobrir os pesos sem testar todos os números.`:`Primeira balança: seus blocos somam ${2*x+y} kg; precisamos de ${t1}. Segunda: somam ${x+2*y} kg; precisamos de ${t2}. Uma só igualdade não basta.`);};bindNext();
}
function logicGame(){
 const levels=[[5,9,1],[6,12,1],[6,11,2],[7,15,1],[8,18,1]], [max,sum,diff]=levels[round%levels.length];let digits=[null,null,null],slot=0;
 gameRoot.innerHTML=`<span class="pill">Lógica e padrões · desafio ${round%levels.length+1} de ${levels.length}</span><h3>O cofre das três pistas</h3><p>A senha tem três algarismos diferentes, de 1 a ${max}. Todas as pistas devem valer juntas.</p><ol><li>A soma dos três algarismos é ${sum}.</li><li>O segundo algarismo é maior que o primeiro.</li><li>O terceiro é ${diff} a mais que o primeiro.</li></ol><p>Selecione uma posição e depois um algarismo.</p><div class="puzzle-digits" id="code-slots">${[0,1,2].map(i=>`<button data-slot="${i}" aria-label="Posição ${i+1}" aria-pressed="${i===0}">${i+1}ª: ?</button>`).join('')}</div><div class="puzzle-digits">${Array.from({length:max},(_,i)=>`<button data-digit="${i+1}">${i+1}</button>`).join('')}</div><button class="primary" id="check-code">Abrir o cofre</button>${tail('Escolha um candidato para o primeiro algarismo. A terceira pista determina o terceiro; a soma determina o segundo. Então confira se todos são diferentes e se o segundo é maior.')}`;
 function paint(){gameRoot.querySelectorAll('[data-slot]').forEach(b=>{const i=+b.dataset.slot;b.textContent=`${i+1}ª: ${digits[i]??'?'}`;b.setAttribute('aria-pressed',String(i===slot));b.classList.toggle('active',i===slot);});}
 gameRoot.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{slot=+b.dataset.slot;paint();});gameRoot.querySelectorAll('[data-digit]').forEach(b=>b.onclick=()=>{digits[slot]=+b.dataset.digit;slot=(slot+1)%3;paint();feedback('Confira as três pistas antes de abrir.');});gameRoot.querySelector('#check-code').onclick=()=>{if(digits.includes(null)){feedback('Preencha as três posições.');return;}const [a,b,c]=digits;const errors=[];if(new Set(digits).size!==3)errors.push('os algarismos precisam ser diferentes');if(a+b+c!==sum)errors.push(`a soma é ${a+b+c}, e deveria ser ${sum}`);if(b<=a)errors.push('o segundo precisa ser maior que o primeiro');if(c!==a+diff)errors.push(`o terceiro precisa ser ${diff} a mais que o primeiro`);feedback(errors.length?'Cofre fechado: '+errors.join('; ')+'.':`Cofre aberto: ${digits.join('')}! Para provar que é a única senha, liste os possíveis primeiros algarismos e elimine os que violam alguma pista.`);};paint();bindNext();
}
function spaceGame(){
 const levels=[[[1,0,0],[2,1,0],[1,1,0]],[[0,1,0],[1,3,1],[0,1,0]],[[1,2,0],[2,1,1],[0,1,2]],[[0,2,1],[1,1,2],[2,0,1]],[[1,1,1],[1,2,1],[1,1,3]]];const target=levels[round%levels.length],height=Array.from({length:3},()=>[0,0,0]);const front=[0,1,2].map(c=>Math.max(...target.map(r=>r[c]))),side=target.map(r=>Math.max(...r)),volume=target.flat().reduce((a,b)=>a+b,0);
 gameRoot.innerHTML=`<span class="pill">Geometria espacial · desafio ${round%levels.length+1} de ${levels.length}</span><h3>Construtor de cubinhos</h3><p>Monte uma construção com <strong>${volume} cubinhos</strong>, sem buracos dentro das colunas. Pode haver mais de uma solução: basta respeitar todas as vistas.</p><p><strong>Vista de frente:</strong> alturas máximas das colunas, da esquerda para a direita: ${front.join(' · ')}.<br><strong>Vista lateral:</strong> alturas máximas das linhas, de cima para baixo no tabuleiro: ${side.join(' · ')}.</p><p class="small">As casas marcadas “usar” precisam ter cubos; as demais ficam vazias. Clique para aumentar a altura: 0 → 1 → 2 → 3 → 0.</p><div class="gameboard" style="grid-template-columns:repeat(3,1fr);max-width:300px">${target.flat().map((v,i)=>`<button data-height="${i}" class="cell" style="aspect-ratio:1.4" ${v?'':'disabled'} aria-label="Linha ${Math.floor(i/3)+1}, coluna ${i%3+1}, altura 0">${v?'Usar: 0':'Vazia'}</button>`).join('')}</div><svg id="cubes-view" class="plot-svg" viewBox="0 0 420 270" role="img" aria-label="Vista isométrica da sua construção"></svg><p id="cubes-count"></p><button id="check-cubes" class="primary">Conferir as três vistas</button>${tail('Na vista de frente, a maior pilha de cada coluna esconde as menores. Na lateral, acontece o mesmo com cada linha. Primeiro monte as pilhas mais altas; depois ajuste o total de cubinhos.')}`;
 function draw(){let svg='';for(let r=0;r<3;r++)for(let c=0;c<3;c++){const x=210+(c-r)*38,y=105+(c+r)*20;svg+=`<path d="M${x},${y} l38,20 -38,20 -38,-20 Z" fill="#e9f2ed" stroke="#819a92"/>`;for(let z=0;z<height[r][c];z++){const yy=y-z*27;svg+=`<path d="M${x-38},${yy-7} l38,20 0,27 -38,-20 Z" fill="#12675b" stroke="#fff"/><path d="M${x},${yy+13} l38,-20 0,27 -38,20 Z" fill="#358c80" stroke="#fff"/><path d="M${x},${yy-27} l38,20 -38,20 -38,-20 Z" fill="#8ac6b4" stroke="#fff"/>`;}}gameRoot.querySelector('#cubes-view').innerHTML=svg;gameRoot.querySelector('#cubes-count').textContent=`Sua construção: ${height.flat().reduce((a,b)=>a+b,0)} de ${volume} cubinhos.`;}
 gameRoot.querySelectorAll('[data-height]').forEach(b=>b.onclick=()=>{const i=+b.dataset.height,r=Math.floor(i/3),c=i%3;height[r][c]=(height[r][c]+1)%4;b.textContent='Usar: '+height[r][c];b.classList.toggle('on',height[r][c]>0);b.setAttribute('aria-label',`Linha ${r+1}, coluna ${c+1}, altura ${height[r][c]}`);draw();feedback('Observe as alturas e o total antes de conferir.');});gameRoot.querySelector('#check-cubes').onclick=()=>{const f=[0,1,2].map(c=>Math.max(...height.map(r=>r[c]))),s=height.map(r=>Math.max(...r)),v=height.flat().reduce((a,b)=>a+b,0);const footprint=target.flat().every((h,i)=>Boolean(h)===Boolean(height.flat()[i]));const ok=footprint&&v===volume&&f.every((n,i)=>n===front[i])&&s.every((n,i)=>n===side[i]);feedback(ok?'Construção aprovada! Todas as vistas e o total coincidem. Pode existir outra construção válida; procure uma e explique por que as vistas não determinam sempre cada pilha.':`Confira: frente ${f.join(', ')}; lateral ${s.join(', ')}; total ${v}.${footprint?'':' Ainda falta ocupar uma casa marcada “usar”.'}`);};draw();bindNext();
}
renderGame();
