'use strict';
const lessons = [
 {title:'Operações, medidas e leitura atenta',goal:'Traduzir uma história em contas e conferir se a resposta faz sentido.',idea:'Antes de calcular, escreva o que a pergunta pede. Adição junta ou aumenta; subtração compara ou retira; multiplicação reúne grupos iguais; divisão reparte ou conta grupos. Respeite os parênteses e faça multiplicações e divisões antes das adições e subtrações. Converta as medidas para a mesma unidade: 1 m = 100 cm; 1 kg = 1.000 g; 1 hora = 60 minutos.',example:'Uma oficina tem 7 caixas com 8 peças cada. Usa 19 peças. Quantas restam? Primeiro contamos todas: 7 × 8 = 56. Depois retiramos as usadas: 56 − 19 = 37. Não é 7 × (8 − 19), pois 19 é o total usado, não o usado em cada caixa.',trap:'Números no enunciado não indicam automaticamente a operação. Leia também a unidade pedida.',questions:[
 ['Uma biblioteca recebeu 6 pacotes com 9 livros cada e emprestou 17 desses livros. Quantos ficaram?','37 livros. São 6 × 9 = 54 recebidos e 54 − 17 = 37 restantes.'],
 ['Uma atividade começa às 14h35 e dura 1 hora e 50 minutos. A que horas termina?','16h25. Uma hora depois são 15h35; mais 25 minutos levam a 16h e os outros 25 a 16h25.'],
 ['Um reservatório tinha certa quantidade de água. Recebeu 18 litros e, depois, metade de toda a água foi usada. Restaram 25 litros. Quanto havia no início? Explique de trás para frente.','32 litros. Antes de usar a metade havia 2 × 25 = 50 litros. Antes de receber os 18 litros havia 50 − 18 = 32. Verificação: (32 + 18) ÷ 2 = 25.']]},
 {title:'Divisibilidade, restos e paridade',goal:'Usar propriedades dos números para evitar tentativas sem organização.',idea:'Um número é divisível por outro quando o resto da divisão é zero. É divisível por 2 se termina em algarismo par; por 3 se a soma dos algarismos é divisível por 3; por 5 se termina em 0 ou 5; por 9 se a soma dos algarismos é divisível por 9. Par + par e ímpar + ímpar dão par; par + ímpar dá ímpar. Divisores ajudam a repartir; múltiplos ajudam a encontrar encontros de ciclos.',example:'Duas luzes piscam juntas agora. Uma pisca a cada 6 segundos e outra a cada 8. Os múltiplos de 6 são 6, 12, 18, 24…; os de 8 são 8, 16, 24… O primeiro encontro futuro é aos 24 segundos.',trap:'“Resto 2 na divisão por 5” significa números como 2, 7, 12, 17… O resto deve ser menor que o divisor.',questions:[
 ['Qual é o menor número maior que 20 que é divisível por 3 e por 4?','24. Os múltiplos de 4 maiores que 20 começam em 24; como 2 + 4 = 6, 24 também é divisível por 3.'],
 ['Um número entre 20 e 40 deixa resto 2 na divisão por 5 e é divisível por 3. Qual é ele?','27. Os candidatos pelo resto são 22, 27, 32 e 37. Só 27 tem soma dos algarismos divisível por 3.'],
 ['É possível escolher três números ímpares cuja soma seja 40? Justifique sem testar todas as escolhas.','Não. Dois ímpares somam um par; esse par somado ao terceiro ímpar dá um ímpar. Como 40 é par, isso é impossível.']]},
 {title:'Frações, decimais e porcentagens',goal:'Reconhecer o inteiro de referência e comparar partes.',idea:'Em 3/4, o denominador 4 indica quantas partes iguais formam o inteiro e o numerador 3 indica quantas usamos. Frações equivalentes representam a mesma quantidade: 1/2 = 2/4 = 0,5 = 50%. Para somar frações, represente-as com partes de mesmo tamanho. Uma porcentagem é uma fração com denominador 100. Para calcular 25% de uma quantidade, tome sua quarta parte.',example:'Uma caixa tem 24 lápis. Um terço é azul e um quarto é vermelho; os demais são verdes. Azuis: 24 ÷ 3 = 8. Vermelhos: 24 ÷ 4 = 6. Verdes: 24 − 8 − 6 = 10. As duas frações se referem à caixa inteira.',trap:'Metade do que restou pode ser diferente de metade do total inicial. Não some denominadores: 1/2 + 1/3 = 3/6 + 2/6 = 5/6.',questions:[
 ['Uma fita de 28 cm foi cortada, retirando-se 3/4 de seu comprimento. Quantos centímetros sobraram?','7 cm. Foram retirados 28 ÷ 4 × 3 = 21 cm, então sobraram 28 − 21 = 7 cm, isto é, 1/4 da fita.'],
 ['Um jogo custa R$ 80 e recebe desconto de 15%. Qual é o novo preço?','R$ 68. Dez por cento são R$ 8; cinco por cento são R$ 4. O desconto é R$ 12 e o preço final é 80 − 12 = 68.'],
 ['Lia leu 1/3 de um livro na segunda-feira. Na terça, leu metade das páginas que ainda faltavam. Que fração do livro falta ler?','1/3. Depois da segunda faltavam 2/3; na terça ela leu metade de 2/3, ou seja, 1/3. Restou o outro 1/3. Desenhe o livro em três partes iguais.']]},
 {title:'Proporções, tabelas e relações',goal:'Descobrir valores desconhecidos por comparação e organização.',idea:'Em situações proporcionais, multiplicar uma quantidade por um fator multiplica a outra pelo mesmo fator. Descobrir o valor de uma unidade costuma ajudar. Mas nem toda relação é proporcional: dobrar a idade de uma pessoa não dobra a idade de outra. Organize dados em tabelas, leia escalas de gráficos e use operações inversas para descobrir valores escondidos.',example:'Quatro ingressos iguais custam R$ 36. Cada um custa 36 ÷ 4 = 9 reais; sete custam 7 × 9 = 63 reais. Essa conclusão usa a condição de que todos têm o mesmo preço, sem descontos.',trap:'Diferencie “três a mais” de “três vezes mais”. Em gráficos, uma divisão no eixo pode valer 5, 10 ou outra quantidade.',questions:[
 ['Três cadernos iguais custam R$ 21. Quanto custam cinco, ao mesmo preço por unidade?','R$ 35. Cada caderno custa 21 ÷ 3 = 7 reais; cinco custam 5 × 7 = 35.'],
 ['Três equipes fizeram 12, 18 e 15 pontos. Quantos pontos fez cada equipe em média?','15 pontos. A soma é 45 e há 3 equipes. A média é 45 ÷ 3 = 15.'],
 ['Duas caixas iguais e um peso de 3 kg somam 17 kg. Quanto pesam três dessas caixas? Explique sem adivinhar.','21 kg. As duas caixas pesam juntas 17 − 3 = 14 kg. Cada caixa pesa 7 kg, então três pesam 21 kg.']]},
 {title:'Geometria plana: área, perímetro e ângulos',goal:'Separar medida de contorno de medida de superfície.',idea:'Perímetro é a soma dos comprimentos da borda. Área mede a superfície: conte quadrados de uma unidade ou decomponha a figura. Um retângulo de lados a e b tem área a × b e perímetro 2 × (a + b). Um triângulo tem metade da área de um retângulo de mesma base e altura: base × altura ÷ 2. Um ângulo reto tem 90°; meia-volta tem 180°; uma volta tem 360°. A soma dos ângulos de um triângulo é 180°.',example:'Um retângulo de 5 cm por 3 cm tem área 15 cm² e perímetro 16 cm. Se juntarmos quadradinhos, cada lado compartilhado desaparece duas vezes do contorno. Por isso, uma figura com n quadradinhos e s pares de lados compartilhados tem perímetro 4n − 2s, em unidades de lado.',trap:'Figuras de mesma área podem ter perímetros diferentes. Não inclua linhas internas no contorno.',questions:[
 ['Um retângulo mede 7 cm por 4 cm. Qual é sua área e qual é seu perímetro?','Área 28 cm² e perímetro 22 cm. A área é 7 × 4; o perímetro é 7 + 4 + 7 + 4.'],
 ['Um triângulo tem ângulos de 45° e 65°. Quanto mede o terceiro ângulo?','70°. A soma é 180°, então o terceiro vale 180 − 45 − 65 = 70°.'],
 ['De um retângulo de 6 cm por 4 cm, recorta-se um quadrado de 2 cm por 2 cm em um canto. Qual é a área restante? O perímetro muda? Desenhe e explique.','Área 20 cm²: 24 − 4 = 20. O perímetro permanece 20 cm: retiramos dois trechos externos de 2 cm e criamos dois trechos internos de 2 cm. Isso depende de o recorte estar no canto.']]},
 {title:'Contagem e chances',goal:'Contar todas as possibilidades, sem repetir nem esquecer casos.',idea:'Use listas, tabelas e árvores. Se cada uma de 3 camisetas combina com cada um de 2 shorts, há 3 × 2 = 6 combinações. Some quantidades de casos que não se sobrepõem. Se a ordem não importa, não conte a mesma escolha duas vezes. Em experiências com resultados igualmente prováveis, a probabilidade é casos favoráveis divididos pelo total de casos.',example:'Com os algarismos 2, 4 e 7, quantos números de dois algarismos distintos podem ser feitos? São 3 escolhas para a dezena e 2 para a unidade: 6 números. Lista: 24, 27, 42, 47, 72, 74.',trap:'“Escolher duas pessoas” não é o mesmo que “escolher presidente e vice”: no segundo caso, os cargos tornam a ordem importante.',questions:[
 ['Uma lanchonete oferece 3 tipos de pão e 4 recheios. Quantos lanches com exatamente um pão e um recheio podem ser escolhidos?','12. Para cada um dos 3 pães há 4 recheios: 3 × 4 = 12.'],
 ['De quantas formas é possível escolher duas pessoas de um grupo com Ana, Beto, Caio e Duda, sem cargos diferentes?','6 pares: Ana–Beto, Ana–Caio, Ana–Duda, Beto–Caio, Beto–Duda e Caio–Duda. A ordem não muda o par.'],
 ['Dois dados comuns e honestos são lançados. Qual é a probabilidade de a soma ser 5? Liste os resultados favoráveis.','1/9. Há 6 × 6 = 36 resultados ordenados igualmente prováveis. Os favoráveis são (1,4), (2,3), (3,2) e (4,1). Assim, a chance é 4/36 = 1/9.']]},
 {title:'Padrões, lógica e estratégias',goal:'Justificar uma regra e eliminar casos impossíveis.',idea:'Em sequências, procure diferenças, repetições ou uma regra de construção. Uma sequência finita pode admitir várias continuações; use a regra dada no problema. Em ciclos, use o resto da divisão. Em problemas de lógica, teste uma hipótese e confira todas as pistas. Para explicar uma impossibilidade, procure algo que não muda, como a paridade.',example:'Uma faixa repete estrela, círculo, triângulo. A posição 1 é estrela. Para descobrir a figura da posição 20, dividimos 20 por 3: resto 2. Ela ocupa a segunda posição do bloco, portanto é um círculo. Resto zero indicaria a terceira figura.',trap:'Um desenho sugere uma regra, mas a justificativa deve explicar por que ela continua valendo.',questions:[
 ['Uma sequência começa em 4 e aumenta 3 a cada passo. Qual é o sexto termo?','19. Os termos são 4, 7, 10, 13, 16, 19. Do primeiro ao sexto há cinco aumentos: 4 + 5 × 3.'],
 ['Uma faixa repete vermelho, azul, amarelo, verde, começando com vermelho. Qual é a cor da posição 31?','Amarelo. Como 31 = 7 × 4 + 3, a posição 31 é a terceira do bloco.'],
 ['Um prêmio está em uma das caixas A, B ou C. A etiqueta de A diz “Está aqui”. A de B diz “Não está aqui”. A de C diz “Não está em A”. Exatamente uma etiqueta é verdadeira. Onde está o prêmio?','Na caixa B. Se estivesse em A, as etiquetas A e B seriam verdadeiras. Se estivesse em B, só C seria verdadeira. Se estivesse em C, B e C seriam verdadeiras. Somente B atende à condição.']]},
 {title:'Geometria espacial e visualização',goal:'Imaginar peças escondidas, faces, camadas e movimentos.',idea:'Um cubo tem 6 faces, 12 arestas e 8 vértices. Para contar cubinhos de um bloco retangular completo, multiplique comprimento × largura × altura. Para pilhas irregulares, conte por camadas ou some as alturas das colunas. Ao observar vistas, lembre que uma peça pode esconder outra. Em dobraduras, acompanhe quais faces ficam vizinhas e quais ficam opostas.',example:'Uma construção tem quatro colunas com alturas 1, 3, 2 e 2, sem espaços vazios embaixo. Há 1 + 3 + 2 + 2 = 8 cubos. Por camadas: 4 na base, 3 na segunda e 1 na terceira, também totalizando 8.',trap:'Uma vista mostra apenas o que está naquela direção. Não suponha que todos os cubos estão visíveis.',questions:[
 ['Um bloco completo tem 4 cubinhos de comprimento, 3 de largura e 2 de altura. Quantos cubinhos o formam?','24. Cada camada tem 4 × 3 = 12; duas camadas têm 24.'],
 ['Um cubo grande feito de 3 × 3 × 3 cubinhos tem toda a superfície externa pintada. Quantos cubinhos têm exatamente duas faces pintadas?','12. Eles ficam no meio das 12 arestas. Os 8 cantos têm três faces pintadas, então não entram na contagem.'],
 ['Uma formiga parte de um vértice de um cubo e anda exatamente três arestas completas, podendo repetir arestas. Ela consegue terminar no ponto inicial? Explique.','Não. Pinte os vértices com duas cores de modo que cada aresta una cores diferentes. Cada passo troca a cor. Depois de três passos, a formiga está na cor oposta à inicial e não pode estar no mesmo vértice. Outra forma: cada movimento muda a paridade da soma das três coordenadas 0 ou 1.']]}
];
document.getElementById('lessons').innerHTML = lessons.map((l,i)=>`<article class="lesson"><span class="pill">Lição ${i+1}</span><h2>${l.title}</h2><p><strong>Missão:</strong> ${l.goal}</p><p>${l.idea}</p><div class="example"><strong>Vamos resolver juntos</strong><p>${l.example}</p></div><p><strong>Olho vivo:</strong> ${l.trap}</p><h3>Agora é sua vez</h3>${l.questions.map((q,j)=>`<div class="exercise"><span class="pill">${['Aquecimento','Prática','Desafio · justifique'][j]}</span><p><strong>${i+1}.${j+1}.</strong> ${q[0]}</p><div class="worklines" aria-hidden="true"></div></div>`).join('')}</article>`).join('');
document.getElementById('solutions').innerHTML = lessons.map((l,i)=>`<details><summary>Lição ${i+1} · ${l.title}</summary>${l.questions.map((q,j)=>`<p><strong>${i+1}.${j+1}.</strong> ${q[1]}</p>`).join('')}</details>`).join('');
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('main > section').forEach(s=>s.classList.toggle('hidden',s.id!==b.dataset.tab));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));}));
let priorDetails=[];
function preparePrint(exercises){document.body.classList.toggle('print-exercises',exercises);priorDetails=Array.from(document.querySelectorAll('details')).map(d=>d.open);document.querySelectorAll('details').forEach(d=>d.open=true);window.print();}
document.getElementById('print-all').onclick=()=>preparePrint(false);
document.getElementById('print-ex').onclick=()=>preparePrint(true);
window.addEventListener('afterprint',()=>{document.body.classList.remove('print-exercises');document.querySelectorAll('details').forEach((d,i)=>d.open=priorDetails[i]||false);});
