(()=>{
const topics=['Operações e medidas','Divisibilidade e restos','Frações e porcentagem','Proporções e relações','Geometria plana','Contagem e chances','Lógica e padrões','Geometria espacial'];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const r=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
const make=(id,t,text,answer,solution,other=[],source=null)=>({id,t,text,answer:String(answer),solution,source,options:shuffle([...new Set([String(answer),...other.map(String),...Array.from({length:12},(_,i)=>String(Math.max(0,Number(answer)+i-5)))])].filter(x=>x!=='NaN').slice(0,5))});
const official=(id,t,text,answer,solution,other,year,number)=>()=>make(id,t,text,answer,solution,other,{year,number,url:OBMEP_BANK.questions.find(q=>q.year===year&&q.phase===1&&q.number===number)?.source});
const adapted=[
 official('o15a',0,'Uma compra de R$ 126,80 foi paga com R$ 200,00. Calcule o troco, em reais.','73,20','Subtraia o preço do valor pago: 200,00 − 126,80 = 73,20.',['71,20','71,80','72,20','72,80'],2015,1),
 official('o15b',3,'Um recipiente com água pesa 10,8 kg. Depois de retirar metade da água, o conjunto pesa 5,7 kg. Qual é a massa do recipiente vazio, em gramas?',600,'A água retirada pesa 10,8 − 5,7 = 5,1 kg. Toda a água pesava 10,2 kg. O recipiente pesa 10,8 − 10,2 = 0,6 kg = 600 g.',[400,500,700,800],2015,4),
 official('o16',1,'Encontre o maior múltiplo de 13 com três algarismos. Quanto vale a soma dos seus algarismos?',25,'13 × 76 = 988; o múltiplo seguinte é 1001. Logo, o número é 988 e a soma é 9 + 8 + 8 = 25.',[23,24,26,27],2016,5),
 official('o18',2,'Três oitavos de um bolo custam R$ 4,50. Mantendo o mesmo preço por fração, quanto custam os cinco oitavos restantes, em reais?','7,50','Cada oitavo custa 4,50 ÷ 3 = 1,50. Cinco oitavos custam 5 × 1,50 = 7,50.',['6,00','6,50','7,00','8,00'],2018,8),
 official('o19',0,'Qual valor de x torna verdadeira a igualdade 17 − 3 = 20 − 16 + x?',10,'O lado esquerdo vale 14. À direita temos 4 + x, então x = 14 − 4 = 10.',[11,12,13,14],2019,1),
 official('o25a',5,'Usando apenas cédulas de R$ 2 e R$ 5, quantas combinações pagam exatamente R$ 20? A ordem das cédulas não conta.',3,'A quantidade de cédulas de 5 precisa ser par: 0, 2 ou 4. Elas combinam, respectivamente, com 10, 5 ou 0 cédulas de 2. São três possibilidades.',[1,2,4,5],2025,1),
 official('o25b',3,'Cada letra tem um valor fixo e o valor de uma palavra é a soma das letras. JABUTI vale 40; CABRA vale 19; JABUTICABA vale 55. Quanto vale R?',4,'JABUTICABA − JABUTI deixa CABA, que vale 55 − 40 = 15. CABRA tem as mesmas letras de CABA e mais R. Portanto, R = 19 − 15 = 4.',[1,2,3,5],2025,3),
 official('o25c',6,'Cinco bolas, numeradas de 1 a 5, têm massas de 1 kg (três bolas) ou 0,5 kg (duas bolas). As bolas 1, 2 e 3 equilibram as bolas 4 e 5. Já 2 e 5 pesam mais que 1 e 4. Qual par pesa 0,5 kg por bola?','1 e 3','A massa total é 4 kg, portanto cada lado da primeira pesagem tem 2 kg. As bolas 4 e 5 pesam 1 kg cada. Entre 1, 2 e 3 há duas leves; a segunda pesagem mostra que 2 é mais pesada que 1. Logo, 1 e 3 são leves.',['1 e 2','2 e 3','1 e 4','2 e 5'],2025,4)
];
const generators=[
 [()=>{let a=r(6,19),b=r(3,8);return [`Pensei em um número, somei ${b} e multipliquei o resultado por 3. Obtive ${(a+b)*3}. Em que número pensei?`,a,`Desfaça as operações: ${(a+b)*3} ÷ 3 − ${b} = ${a}.`]},
 ()=>{let a=r(4,9),b=r(3,8);return [`Um ônibus sai às 8h${a*5 <10?'0':''}${a*5} e viaja por ${b*10} minutos. Quantos minutos depois das 8h ele chega?`,a*5+b*10,`Some os minutos iniciais e a duração: ${a*5} + ${b*10} = ${a*5+b*10} minutos depois das 8h.`]},
 ()=>{let a=r(3,9),b=r(4,8);return [`Há ${a} caixas com ${b} lápis em cada uma. Depois de distribuir ${a} lápis, quantos restam?`,a*(b-1),`Havia ${a} × ${b} = ${a*b}. Restam ${a*b} − ${a} = ${a*(b-1)}.`]}],
 [()=>{let a=r(4,9),b=r(5,15),c=r(1,a-1);return [`Qual é o resto da divisão de ${a*b+c} por ${a}?`,c,`${a*b+c} = ${a} × ${b} + ${c}, com resto menor que ${a}.`]},
 ()=>{let a=r(3,9),b=r(5,12);return [`Quantos múltiplos positivos de ${a} são menores ou iguais a ${a*b+2}?`,b,`Eles vão de ${a} × 1 até ${a} × ${b}. O próximo, ${a*(b+1)}, ultrapassa o limite.`]},
 ()=>{let a=r(3,10);return [`Qual é a soma dos ${a} primeiros números ímpares positivos?`,a*a,`Os ímpares são 1, 3, …, ${2*a-1}. A média do primeiro e do último é ${a}. Multiplicando por ${a} termos: ${a*a}.`]}],
 [()=>{let a=r(4,12);return [`Uma turma tem ${a*4} alunos. Três quartos vieram de ônibus. Quantos vieram de outra forma?`,a,`Resta um quarto: ${a*4} ÷ 4 = ${a}.`]},
 ()=>{let a=r(4,15);return [`Um produto de R$ ${a*10} recebe desconto de 20%. Qual é o preço final, em reais?`,a*8,`20% são R$ ${a*2}. O preço final é ${a*10} − ${a*2} = ${a*8}.`]},
 ()=>{let a=r(3,12);return [`Lia leu metade de um livro de ${a*6} páginas e depois um terço das páginas restantes. Quantas páginas ainda faltam?`,a*2,`Depois da metade faltam ${a*3}. Ela lê mais ${a}, deixando ${a*2}.`]}],
 [()=>{let a=r(3,8),b=r(4,9);return [`${a} cadernos iguais custam R$ ${a*b}. Ao mesmo preço unitário, quanto custam ${a+2} cadernos, em reais?`,(a+2)*b,`Cada caderno custa ${a*b} ÷ ${a} = ${b}. O total é ${a+2} × ${b} = ${(a+2)*b}.`]},
 ()=>{let a=r(3,10),b=r(2,7);return [`Duas caixas iguais e um peso de ${b} kg totalizam ${2*a+b} kg. Quanto pesam três caixas, em kg?`,a*3,`Retirando o peso, duas caixas têm ${a*2} kg. Cada caixa tem ${a} kg e três têm ${a*3} kg.`]},
 ()=>{let a=r(10,25),b=r(2,6);return [`Três equipes marcaram ${a-b}, ${a} e ${a+b} pontos. Qual é a média?`,a,`A soma é ${a*3}. Dividindo por três equipes, a média é ${a}.`]}],
 [()=>{let a=r(5,12),b=r(3,4);return [`De um retângulo de ${a} cm por ${b} cm, retire um quadrado de 2 cm de lado de um canto. Qual é a área restante, em cm²?`,a*b-4,`A área inicial é ${a*b}; o recorte tem área 4. Restam ${a*b-4} cm².`]},
 ()=>{let a=r(4,12),b=r(3,9);return [`Um retângulo tem área ${a*b} cm² e um lado de ${a} cm. Qual é o perímetro, em cm?`,2*(a+b),`O outro lado mede ${a*b} ÷ ${a} = ${b}. Perímetro: 2 × (${a} + ${b}) = ${2*(a+b)}.`]},
 ()=>{let a=r(3,7)*10,b=r(3,7)*10;return [`Dois ângulos de um triângulo medem ${a}° e ${b}°. Quanto mede o terceiro?`,180-a-b,`A soma é 180°. Subtraia ${a} e ${b}: ${180-a-b}°.`]}],
 [()=>{let a=r(3,8),b=r(2,6);return [`Uma loja oferece ${a} camisetas e ${b} bonés diferentes. Quantos conjuntos com uma camiseta e um boné podem ser escolhidos?`,a*b,`Para cada camiseta há ${b} bonés: ${a} × ${b} = ${a*b}.`]},
 ()=>{let a=r(4,9);return [`Quantas duplas diferentes podem ser formadas em um grupo de ${a} pessoas, sem cargos distintos?`,a*(a-1)/2,`Escolher a primeira e depois a segunda dá ${a} × ${a-1}. Cada dupla foi contada duas vezes; divida por 2: ${a*(a-1)/2}.`]},
 ()=>{let a=r(3,7);return [`Com ${a} algarismos diferentes, todos não nulos, quantos números de dois algarismos distintos podem ser escritos?`,a*(a-1),`Há ${a} escolhas para a dezena e ${a-1} para a unidade: ${a*(a-1)}.`]}],
 [()=>{let a=r(2,8),b=r(3,7),n=r(7,15);return [`Uma sequência começa em ${a} e aumenta sempre ${b}. Qual é o ${n}º termo?`,a+(n-1)*b,`Do primeiro ao ${n}º há ${n-1} aumentos: ${a} + ${n-1} × ${b} = ${a+(n-1)*b}.`]},
 ()=>{let n=r(15,50);let colors=['vermelha','azul','amarela'];return [`Uma faixa repete vermelha, azul, amarela, começando na posição 1. Qual é a cor da posição ${n}?`,colors[(n-1)%3],`Divida ${n} por 3. Resto 1 indica vermelha; 2, azul; 0, amarela. O resto é ${n%3}.`,['vermelha','azul','amarela','verde','roxa']]},
 ()=>{let a=r(4,15);return [`Uma peça ocupa a casa ${a} de uma trilha numerada. Cada movimento avança exatamente 2 casas. Qual casa ela alcança após 7 movimentos?`,a+14,`Sete movimentos avançam 14 casas: ${a} + 14 = ${a+14}.`]}],
 [()=>{let a=r(3,6),b=r(2,5),c=r(2,4);return [`Um bloco completo tem ${a} cubinhos de comprimento, ${b} de largura e ${c} de altura. Quantos cubinhos o compõem?`,a*b*c,`Cada camada tem ${a*b} cubinhos. São ${c} camadas: ${a*b*c}.`]},
 ()=>{let a=r(3,7);return [`Um cubo feito de ${a} × ${a} × ${a} cubinhos tem a superfície externa pintada. Quantos cubinhos têm exatamente duas faces pintadas?`,12*(a-2),`São os cubinhos das arestas, excluindo os cantos. Há ${a-2} por aresta e 12 arestas: ${12*(a-2)}.`]},
 ()=>{let a=r(3,7);return [`Um cubo de ${a} × ${a} × ${a} cubinhos é pintado por fora. Quantos cubinhos ficam sem nenhuma face pintada?`,(a-2)**3,`Retire mentalmente a camada externa de cada lado. O interior tem (${a} − 2)³ = ${(a-2)**3} cubinhos.`]}]
];
function pool(mode,topic,origin){let out=[];if(mode==='1'&&origin!=='author')out.push(...adapted.map(f=>f()));if(origin!=='official'||mode==='2')generators.forEach((group,t)=>group.forEach((f,k)=>{const [text,answer,solution,other]=f();out.push(make(`a${t}-${k}`,t,text,answer,solution,other))}));return out.filter(q=>topic==='all'||q.t===Number(topic))}
const root=document.getElementById('simulator');const key='obmep-simulado-v1';let exam=null;try{exam=JSON.parse(localStorage.getItem(key))}catch{}
if(!exam||exam.version!==1||!Array.isArray(exam.questions)||!exam.questions.length)exam=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem(key,JSON.stringify(exam))}catch{document.getElementById('sim-save').textContent='Não foi possível salvar neste navegador. Mantenha esta aba aberta.'}};
root.innerHTML=`<h2>Uma nova prova a cada sorteio</h2><p>Leia e resolva tudo aqui, sem abrir outro site. Os enunciados adaptados de provas oficiais têm referência; os autorais recebem novos valores a cada sorteio. Este é um treino, não uma prova oficial.</p><div class="filters"><label>Formato<select id="sim-mode"><option value="1">Alternativas · treino da 1ª fase</option><option value="2">Discursivo · justificar o raciocínio</option></select></label><label>Tema<select id="sim-topic"><option value="all">Todos os temas</option>${topics.map((t,i)=>`<option value="${i}">${t}</option>`).join('')}</select></label><label>Questões<select id="sim-size"><option>5</option><option>10</option><option selected>20</option></select></label><label>Banco<select id="sim-origin"><option value="mixed">Oficiais adaptadas + autorais</option><option value="official">Só oficiais adaptadas</option><option value="author">Só autorais</option></select></label><button id="sim-start" class="primary">Sortear nova prova</button></div><p id="sim-availability" class="small"></p><p id="sim-save" class="small">O simulado fica salvo neste navegador. Recarregar retoma a prova; “Sortear nova prova” reinicia com outro sorteio.</p><div id="sim-content" aria-live="polite"></div>`;
const el=id=>document.getElementById(id);const config=()=>[el('sim-mode').value,el('sim-topic').value,el('sim-origin').value];
function available(){el('sim-origin').disabled=el('sim-mode').value==='2';let n=pool(...config()).length;el('sim-availability').textContent=`${n} modelos disponíveis neste filtro. Se pedir mais, usamos todos, sem repetir modelos na mesma prova. No discursivo, os problemas são autorais e a correção é uma autoavaliação.`;el('sim-start').disabled=!n}
['sim-mode','sim-topic','sim-origin'].forEach(id=>el(id).onchange=available);available();
el('sim-start').onclick=()=>{if(exam&&!exam.done){renderRestart();return}start()};
function renderRestart(){el('sim-content').insertAdjacentHTML('afterbegin',`<div id="sim-confirm" class="note">Trocar a prova apaga as respostas deste simulado.<div class="row"><button id="sim-replace">Descartar e sortear outra</button><button id="sim-keep">Continuar esta prova</button></div></div>`);el('sim-start').disabled=true;el('sim-replace').onclick=()=>{available();start()};el('sim-keep').onclick=()=>{el('sim-confirm').remove();available()}}
function start(){const [mode,topic,origin]=config();let questions=shuffle(pool(mode,topic,origin)).slice(0,Number(el('sim-size').value));if(exam&&questions.length>1&&questions.map(q=>q.id).join()===exam.questions.map(q=>q.id).join())questions.push(questions.shift());exam={version:1,code:Date.now().toString(36).toUpperCase(),mode,questions,answers:{},drafts:{},self:{},index:0,done:false};save();render()}
function render(){if(!exam){el('sim-content').innerHTML='<div class="card"><h3>Seu caderno está pronto para começar</h3><p>Escolha um tema ou misture os oito. Marque respostas, volte às questões e finalize quando quiser ver a correção.</p></div>';return}if(exam.done){results();return}let q=exam.questions[exam.index];const answered=Object.values(exam.answers).filter(x=>x!==null&&x!=='').length;
el('sim-content').innerHTML=`<div class="toolbar"><strong>Prova ${exam.code} · ${answered}/${exam.questions.length} respondidas</strong><button id="sim-finish">Finalizar e corrigir</button></div><div class="sim-map" aria-label="Navegar pelas questões">${exam.questions.map((x,i)=>`<button data-sim-go="${i}" class="${i===exam.index?'active':''}" aria-current="${i===exam.index?'step':'false'}" aria-label="Questão ${i+1}${exam.answers[i]!=null&&exam.answers[i]!==''?', respondida':''}">${i+1}${exam.answers[i]!=null&&exam.answers[i]!==''?' ✓':''}</button>`).join('')}</div><article class="card"><span class="pill">${topics[q.t]}</span><p class="small">${q.source?`Adaptada da OBMEP ${q.source.year} · Nível 1 · 1ª fase · Q${q.source.number}. Redação e alternativas reorganizadas.`:'Problema autoral · valores sorteados'}</p><h3>Questão ${exam.index+1}</h3><p class="sim-statement">${escape(q.text)}</p>${exam.mode==='1'?`<fieldset class="sim-options"><legend>Escolha uma alternativa</legend>${q.options.map((o,i)=>`<label><input type="radio" name="sim-answer" value="${i}" ${exam.answers[exam.index]===i?'checked':''}> <strong>${'ABCDE'[i]}.</strong> ${escape(o)}</label>`).join('')}</fieldset>`:`<label for="sim-discursive">Resposta e justificativa: mostre suas contas e explique por que funcionam.</label><textarea id="sim-discursive">${escape(exam.answers[exam.index]||'')}</textarea>`}<details><summary>Rascunho</summary><textarea id="sim-draft" aria-label="Rascunho da questão">${escape(exam.drafts[exam.index]||'')}</textarea></details><div class="row"><button id="sim-prev" ${exam.index===0?'disabled':''}>Anterior</button><button id="sim-next" ${exam.index===exam.questions.length-1?'disabled':''}>Próxima</button></div></article>`;
root.querySelectorAll('[data-sim-go]').forEach(b=>b.onclick=()=>{exam.index=Number(b.dataset.simGo);save();render()});
root.querySelectorAll('[name=sim-answer]').forEach(b=>b.onchange=()=>{exam.answers[exam.index]=Number(b.value);save();render()});
if(el('sim-discursive'))el('sim-discursive').oninput=e=>{exam.answers[exam.index]=e.target.value;save()};
el('sim-draft').oninput=e=>{exam.drafts[exam.index]=e.target.value;save()};
el('sim-prev').onclick=()=>{exam.index--;save();render()};el('sim-next').onclick=()=>{exam.index++;save();render()};el('sim-finish').onclick=()=>{const missing=exam.questions.filter((q,i)=>exam.answers[i]==null||exam.answers[i]==='').length;el('sim-content').insertAdjacentHTML('afterbegin',`<div class="note" id="sim-finish-confirm">${missing?`${missing} questão(ões) sem resposta. `:''}Mostrar o resultado encerra esta prova.<div class="row"><button id="sim-end">Encerrar e mostrar soluções</button><button id="sim-return">Voltar à prova</button></div></div>`);el('sim-finish').disabled=true;el('sim-end').onclick=()=>{exam.done=true;save();render()};el('sim-return').onclick=render};}
function results(){let correct=0;exam.questions.forEach((q,i)=>{if(q.options[exam.answers[i]]===q.answer)correct++});let stats=topics.map((t,k)=>{const qs=exam.questions.map((q,i)=>({q,i})).filter(x=>x.q.t===k);return qs.length?`<li>${t}: ${qs.filter(({q,i})=>q.options[exam.answers[i]]===q.answer).length}/${qs.length}</li>`:''}).join('');el('sim-content').innerHTML=`<div class="card"><h3>${exam.mode==='1'?`${correct} de ${exam.questions.length} acertos`:'Compare e avalie suas justificativas'}</h3><p>Prova ${exam.code}. Use “Sortear nova prova” para outra versão.</p>${exam.mode==='1'?`<ul>${stats}</ul>`:'<p>A resposta numérica não basta: confira se você explicou cada etapa. A avaliação abaixo é feita por você, sem nota automática.</p>'}</div>${exam.questions.map((q,i)=>`<article class="card"><span class="pill">${topics[q.t]}</span><h3>Questão ${i+1} ${exam.mode==='1'?(q.options[exam.answers[i]]===q.answer?'· Correta':'· Revisar'):''}</h3><p>${escape(q.text)}</p><p><strong>Sua resposta:</strong> ${escape(exam.mode==='1'?(q.options[exam.answers[i]]??'Em branco'):(exam.answers[i]||'Em branco'))}</p><p><strong>Resposta esperada:</strong> ${escape(q.answer)}</p><div class="example">${escape(q.solution)}</div>${q.source?`<p class="small">Adaptada da OBMEP ${q.source.year}, 1ª fase, Q${q.source.number}. <a href="${q.source.url}" target="_blank" rel="noopener">Consultar original (opcional)</a></p>`:'<p class="small">Problema autoral.</p>'}${exam.mode==='2'?`<label>Minha justificativa <select data-self="${i}"><option value="">Escolher</option><option value="alone" ${exam.self[i]==='alone'?'selected':''}>Consegui explicar sozinho</option><option value="help" ${exam.self[i]==='help'?'selected':''}>Entendi com ajuda da solução</option><option value="review" ${exam.self[i]==='review'?'selected':''}>Preciso revisar</option></select></label>`:''}</article>`).join('')}`;root.querySelectorAll('[data-self]').forEach(s=>s.onchange=()=>{exam.self[s.dataset.self]=s.value;save()})}
render();if(location.hash==='#simulado')document.querySelector('[data-tab=simulator]').click();window.obmepSimulator={pool,getExam:()=>exam};
})();
