const {chromium}=require('/Users/rafaelviana/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Chromium.app/Contents/MacOS/Chromium'});const page=await browser.newPage({viewport:{width:1250,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.context().setOffline(true);
for(const file of ['index.html','output/banco-e-jogos.html']){
await page.goto('file:///Users/rafaelviana/Documents/ChatGPT/OBMEP/'+file);
await page.evaluate(async()=>{if(Object.keys(OBMEP_IMAGES).length!==240)throw Error('Missing crops');for(const q of OBMEP_BANK.questions){const a=OBMEP_IMAGES[q.id];if(!a)throw Error(q.id);const im=new Image;im.src=a.src;await im.decode();if(im.naturalWidth!==a.width||im.naturalHeight!==a.height||im.naturalWidth<400)throw Error(q.id)}});
await page.locator('#bank-year').selectOption('2025');await page.locator('#bank-phase').selectOption('1');await page.locator('#bank-search').fill('Peso do material');await page.locator('[data-open]').first().click();await page.locator('#question-image').evaluate(im=>im.decode());assert((await page.locator('#question-image').getAttribute('alt')).includes('questão 8'));assert.equal(await page.locator('#question-dialog iframe').count(),0);assert(!(await page.locator('#question-dialog').innerText()).includes('procure a página'));await page.locator('#zoom-question').click();assert.equal(await page.locator('#zoom-question').getAttribute('aria-pressed'),'true');await page.locator('#zoom-question').click();await page.locator('#question-dialog').evaluate(d=>d.scrollTop=0);await page.screenshot({path:'tmp/recortes/questao-desktop.png'});
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tmp/recortes/questao-mobile.png'});await page.locator('#close-question').click();await page.locator('#bank-search').fill('');await page.locator('#bank-phase').selectOption('2');await page.locator('[data-open]').first().click();await page.locator('#question-image').evaluate(im=>im.decode());assert.equal(await page.locator('[data-answer]').count(),0);assert(await page.locator('#question-image').isVisible());await page.locator('#close-question').click();await page.setViewportSize({width:1250,height:1050});
}
assert.deepEqual(errors,[]);await browser.close();console.log('OK: all 240 crop images decode offline in index and standalone; Q8 matches, zoom and mobile work, phase 2 inline.');})();
