const {chromium}=require('/Users/rafaelviana/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert');
const fs=require('fs');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Chromium.app/Contents/MacOS/Chromium'});
const page=await browser.newPage({viewport:{width:1250,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///Users/rafaelviana/Documents/ChatGPT/OBMEP/output/banco-e-jogos.html');
await page.evaluate(()=>{localStorage.removeItem('obmep-laboratorio-v2');});await page.reload();
assert((await page.locator('#bank-count').innerText()).includes('214'));
assert.equal(await page.locator('.topic-card').count(),8);
await page.locator('#bank-year').selectOption('all');assert((await page.locator('#bank-count').innerText()).includes('240'));
await page.locator('#bank-phase').selectOption('1');assert((await page.locator('#bank-count').innerText()).includes('180'));
await page.locator('#bank-phase').selectOption('2');assert((await page.locator('#bank-count').innerText()).includes('60'));
await page.locator('#bank-year').selectOption('2021');assert((await page.locator('#bank-count').innerText()).includes('6'));
await page.locator('#bank-phase').selectOption('1');assert(await page.locator('#start-training').isDisabled());
await page.locator('#bank-year').selectOption('2025');await page.locator('#bank-topic').selectOption('3');
const selected=await page.evaluate(()=>window.obmepBankUI.filtered().map(q=>q.id));assert(selected.length>0);
await page.locator('#bank-results [data-open]').first().click();
await page.locator('#draft-answer').fill('Meu raciocínio de teste.');
let id=selected[0];let answer=await page.evaluate(id=>OBMEP_BANK.questions.find(q=>q.id===id).answer,id);
await page.locator(`[data-answer="${answer}"]`).click();await page.locator('#check-official').click();assert((await page.locator('#official-feedback').innerText()).includes('Correto'));
await page.locator('#close-question').click();await page.reload();
assert(await page.evaluate(id=>JSON.parse(localStorage.getItem('obmep-laboratorio-v2'))[id].status==='correct',id));
await page.locator('#bank-year').selectOption('2025');await page.locator('#bank-phase').selectOption('2');await page.locator('#bank-results [data-open]').first().click();assert.equal(await page.locator('[data-answer]').count(),0);
await page.route('https://drive.google.com/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<p>Visualizador simulado somente neste teste.</p>'}));
await page.locator('#reveal-solution').click();await page.locator('[data-self="help"]').click();assert((await page.locator('#official-feedback').innerText()).includes('Autoavaliação'));
await page.locator('#close-question').click();await page.locator('#bank-phase').selectOption('');await page.locator('#bank-length').selectOption('5');await page.locator('#start-training').click();for(let i=0;i<5;i++)await page.locator('#next-training').click();assert((await page.locator('#question-dialog').innerText()).includes('Pulada / não avaliada'));await page.locator('#finish-close').click();
await page.locator('[data-tab="study"]').click();assert.equal(await page.locator('.exercise').count(),40);assert.equal(await page.locator('.lesson').count(),8);
await page.locator('[data-tab="games"]').click();assert.equal(await page.locator('#game-select option').count(),8);
await page.locator('[data-inverse="0"]').click();await page.locator('[data-inverse="1"]').click();await page.locator('[data-inverse="2"]').click();assert((await page.locator('#game .answer').innerText()).includes('recuperou'));
await page.locator('#game-select').selectOption('balance');await page.locator('#weight-a').fill('2');await page.locator('#weight-b').fill('3');await page.locator('#game form button').click();assert((await page.locator('#game .answer').innerText()).includes('equilibraram'));
await page.locator('#game-select').selectOption('logic');for(const d of [2,4,3])await page.locator(`[data-digit="${d}"]`).click();await page.locator('#check-code').click();assert((await page.locator('#game .answer').innerText()).includes('Cofre aberto'));
const unique=await page.evaluate(()=>[[5,9,1],[6,12,1],[6,11,2],[7,15,1],[8,18,1]].map(([max,sum,diff])=>{let n=0;for(let a=1;a<=max;a++)for(let b=1;b<=max;b++)for(let c=1;c<=max;c++)if(new Set([a,b,c]).size===3&&a+b+c===sum&&b>a&&c===a+diff)n++;return n;}));assert.deepEqual(unique,[1,1,1,1,1]);
await page.locator('#game-select').selectOption('space');for(const [i,h] of [[0,1],[3,2],[4,1],[6,1],[7,1]])for(let k=0;k<h;k++)await page.locator(`[data-height="${i}"]`).click();await page.locator('#check-cubes').click();assert((await page.locator('#game .answer').innerText()).includes('aprovada'));
await page.locator('#game-select').selectOption('coins');for(const [a,b] of [[6,0],[3,2],[0,4]]){await page.locator('#coin-a').fill(String(a));await page.locator('#coin-b').fill(String(b));await page.locator('#game form button').click();}assert((await page.locator('#game .answer').innerText()).includes('todas as 3'));
await page.locator('#game-select').selectOption('fractions');for(let i=0;i<4;i++)await page.locator('#game .cell').nth(i).click();await page.locator('#game .check').click();assert((await page.locator('#game .answer').innerText()).includes('Isso!'));
await page.locator('#game-select').selectOption('area');for(const i of [0,1,2,6,7,8])await page.locator('#game .cell').nth(i).click();await page.locator('#game .check').click();assert((await page.locator('#game .answer').innerText()).includes('concluída'));
await page.locator('#game-select').selectOption('nim');for(let i=0;i<4;i++)await page.locator('[data-take="3"]').click();assert((await page.locator('#game .answer').innerText()).includes('venceu!'));
await page.locator('[data-tab="bank"]').click();await page.locator('#bank-year').selectOption('');await page.locator('#bank-phase').selectOption('');await page.screenshot({path:'tmp/banco-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tmp/banco-mobile.png',fullPage:true});
await page.locator('[data-tab="games"]').click();await page.locator('#game-select').selectOption('space');await page.screenshot({path:'tmp/espaco-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);await page.evaluate(()=>localStorage.removeItem('obmep-laboratorio-v2'));await browser.close();console.log('OK: 240 registros, filtros/contagens, primeira e segunda fase, persistência, treinos, 40 exercícios, oito jogos, unicidade dos cofres e layout móvel.');
})();
